(define-library (silex parser)
  (import (scheme base)
          (scheme char)
          (scheme file)
          (scheme write))

  (export parser)

  (include "util.scm")
  (include "tables/action.scm")
  (include "tables/class.scm")
  (include "tables/macro.scm")
  (include "tables/regexp.scm")
  (include "tables/string.scm")
  (include "multilex.scm")
  (include "lexparser.scm"))
